
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author npcnp
 */
public class Calc6 extends javax.swing.JFrame {

    /**
     * Creates new form Calc6
     */
    public Calc6() 
    {
        initComponents();
        lblCurrentLoanTerm.setVisible(false);
        lblTimeRemaining.setVisible(false);
        txtOriginalLoanTerm.setVisible(false);
        txtTimeRemainingYears.setVisible(false);
        txtTimeRemainingMonths.setVisible(false);
        lblYears.setVisible(false);
        lblYears1.setVisible(false);
        lblMonths.setVisible(false);
        
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lblPercent1 = new javax.swing.JLabel();
        lblYears = new javax.swing.JLabel();
        lblYears1 = new javax.swing.JLabel();
        lblMonths = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        lblCurrentLoan = new javax.swing.JLabel();
        cboxOptions = new javax.swing.JComboBox<>();
        lblCurrentLoanAmount = new javax.swing.JLabel();
        txtCurrentLoanAmount = new javax.swing.JTextField();
        lblMonthlyPayment = new javax.swing.JLabel();
        txtCurrentMonthlyPayment = new javax.swing.JTextField();
        lblCurrentInterestRate = new javax.swing.JLabel();
        lblCurrentLoanTerm = new javax.swing.JLabel();
        txtCurrentInterestRate = new javax.swing.JTextField();
        txtOriginalLoanTerm = new javax.swing.JTextField();
        txtTimeRemainingYears = new javax.swing.JTextField();
        txtTimeRemainingMonths = new javax.swing.JTextField();
        lblTimeRemaining = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblPercent2 = new javax.swing.JLabel();
        txtCashOutAmount = new javax.swing.JTextField();
        lblNewLoan = new javax.swing.JLabel();
        lblNewLoanTerm = new javax.swing.JLabel();
        lblNewInterestRate = new javax.swing.JLabel();
        lblPoints = new javax.swing.JLabel();
        txtNewLoanMonths = new javax.swing.JTextField();
        txtNewInterestRate = new javax.swing.JTextField();
        txtPoints = new javax.swing.JTextField();
        txtCostFees = new javax.swing.JTextField();
        lblCostsFees = new javax.swing.JLabel();
        lblCashOut = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOutput = new javax.swing.JTable();
        btnCalculate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblResults = new javax.swing.JLabel();
        lblAprOutput = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setUndecorated(true);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 101, 0));

        lblPercent1.setText("%");

        lblYears.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblYears.setText("Year(s)");

        lblYears1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblYears1.setText("Year(s)");

        lblMonths.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMonths.setText("Months");

        jPanel5.setBackground(new java.awt.Color(96, 0, 21));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Refinance Calculator");
        jLabel2.setToolTipText("");

        closeButton.setText("Back");
        closeButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeButton)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lblCurrentLoan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCurrentLoan.setForeground(new java.awt.Color(255, 255, 255));
        lblCurrentLoan.setText("Current Loan");
        lblCurrentLoan.setToolTipText("");

        cboxOptions.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I know my remaining balance", "I know the original loan amount" }));
        cboxOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxOptionsActionPerformed(evt);
            }
        });

        lblCurrentLoanAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCurrentLoanAmount.setText("Remaining Balance:");

        txtCurrentLoanAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCurrentLoanAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCurrentLoanAmountKeyTyped(evt);
            }
        });

        lblMonthlyPayment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMonthlyPayment.setText("Monthly payment:");

        txtCurrentMonthlyPayment.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCurrentMonthlyPayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCurrentMonthlyPaymentKeyTyped(evt);
            }
        });

        lblCurrentInterestRate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCurrentInterestRate.setText("Interest Rate:");

        lblCurrentLoanTerm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCurrentLoanTerm.setText("Loan Term:");

        txtCurrentInterestRate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCurrentInterestRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCurrentInterestRateKeyTyped(evt);
            }
        });

        txtOriginalLoanTerm.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtOriginalLoanTerm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOriginalLoanTermKeyTyped(evt);
            }
        });

        txtTimeRemainingYears.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTimeRemainingYears.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTimeRemainingYearsKeyTyped(evt);
            }
        });

        txtTimeRemainingMonths.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTimeRemainingMonths.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTimeRemainingMonthsKeyTyped(evt);
            }
        });

        lblTimeRemaining.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTimeRemaining.setText("Time Remaning:");

        lblYear.setText("Year(s)");

        lblPercent2.setText("%");

        txtCashOutAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCashOutAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCashOutAmountKeyTyped(evt);
            }
        });

        lblNewLoan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNewLoan.setForeground(new java.awt.Color(255, 255, 255));
        lblNewLoan.setText("New Loan");

        lblNewLoanTerm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNewLoanTerm.setText("New Loan Term:");

        lblNewInterestRate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNewInterestRate.setText("Interest Rate:");

        lblPoints.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPoints.setText("Points:");

        txtNewLoanMonths.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNewLoanMonths.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNewLoanMonthsKeyTyped(evt);
            }
        });

        txtNewInterestRate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNewInterestRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNewInterestRateKeyTyped(evt);
            }
        });

        txtPoints.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPoints.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPointsKeyTyped(evt);
            }
        });

        txtCostFees.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCostFees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostFeesKeyTyped(evt);
            }
        });

        lblCostsFees.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCostsFees.setText("Costs and Fees:");

        lblCashOut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCashOut.setText("Cash Out Amount:");

        tblOutput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Current Loan", "New Loan", "Difference"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOutput);

        btnCalculate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnCalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalculateMouseClicked(evt);
            }
        });
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        lblResults.setForeground(new java.awt.Color(255, 255, 255));

        lblAprOutput.setForeground(new java.awt.Color(255, 255, 255));

        btnHelp.setText("Help");
        btnHelp.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHelpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboxOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblCurrentLoanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblMonthlyPayment)
                                                    .addComponent(lblCurrentInterestRate)
                                                    .addComponent(lblCurrentLoanTerm))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(txtTimeRemainingMonths, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtTimeRemainingYears, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lblMonths)
                                                            .addComponent(lblYears, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addComponent(txtOriginalLoanTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblYears1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(txtCurrentLoanAmount, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtCurrentMonthlyPayment, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtCurrentInterestRate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblPercent1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addComponent(lblTimeRemaining)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(lblCurrentLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblResults, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAprOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblNewInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCostsFees, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCashOut, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(lblNewLoanTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCostFees)
                                    .addComponent(txtPoints)
                                    .addComponent(txtNewLoanMonths)
                                    .addComponent(txtNewInterestRate)
                                    .addComponent(txtCashOutAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPercent2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(137, 137, 137))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(lblNewLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHelp)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblCurrentLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboxOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCurrentLoanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCurrentLoanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMonthlyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCurrentMonthlyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPercent1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCurrentInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCurrentInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYears1)
                            .addComponent(lblCurrentLoanTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOriginalLoanTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblNewLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNewLoanTerm)
                            .addComponent(txtNewLoanMonths, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNewInterestRate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNewInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPercent2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCostFees, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCostsFees, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCashOut, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCashOutAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTimeRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTimeRemainingYears, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYears))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTimeRemainingMonths, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMonths))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAprOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblResults, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeButtonMouseClicked

    private void txtCurrentLoanAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurrentLoanAmountKeyTyped
        Helper.consumeNotNumbersAllowDecimalLongLength(txtCurrentLoanAmount, evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentLoanAmountKeyTyped

    private void txtCurrentMonthlyPaymentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurrentMonthlyPaymentKeyTyped
        Helper.consumeNotNumbersAllowDecimalLongLength(txtCurrentMonthlyPayment, evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentMonthlyPaymentKeyTyped

    private void txtCurrentInterestRateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurrentInterestRateKeyTyped
        Helper.consumeNotNumbersAllowDecimal(txtCurrentInterestRate, evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentInterestRateKeyTyped

    private void txtNewLoanMonthsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewLoanMonthsKeyTyped
        Helper.consumeNotNumbersAllowDecimal(txtNewLoanMonths, evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewLoanMonthsKeyTyped

    private void txtNewInterestRateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewInterestRateKeyTyped
        Helper.consumeNotNumbersAllowDecimal(txtNewInterestRate, evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewInterestRateKeyTyped

    private void txtPointsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPointsKeyTyped
        Helper.consumeNotNumbersAllowDecimal(txtPoints, evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtPointsKeyTyped

    private void txtCostFeesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostFeesKeyTyped
        Helper.consumeNotNumbersAllowDecimalLongLength(txtCostFees, evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostFeesKeyTyped

    private void txtCashOutAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashOutAmountKeyTyped
        Helper.consumeNotNumbersAllowDecimalAndNeg(txtCashOutAmount, evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtCashOutAmountKeyTyped

    private void btnCalculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalculateMouseClicked
        
        double currentLoanAmount = 0;
        double currentMonthlyPayment = 0; 
        double originalLoanTerm = 0; 
        double originalLoanRemainingMonths = 0; 
        double originalLoanRemainingYears = 0;
        double currentInterestRate; 
        double newLoanMonths; 
        double newInterestRate; 
        double points;
        double pointsCost = 0;
        double costFees; 
        double cashOutAmount;
        double currentAccumulatedInterest = 0;
        double newAccumulatedInterest = 0;
        double totalCurrentMonthlyPayments = 0;
        double totalNewMonthlyPayments = 0;
        double currentLoanMonths = 0;
        double newMonthlyPayment = 0;
        double originalLoanMonthlyPayment = 0;
        double newPrincipalOriginal = 0;
        double newPrincipalFinal = 0;  //placeholder var dependent on option choice for balance
        double timeDifference = 0;
        double originalLoanInterest = 0;
        double AprPrincipal = 0;
        double tolerance = 0.000001; // Tolerance for accuracy
        
        // remaining balance
        if (txtCurrentLoanAmount.getText().equals("") || Double.parseDouble(txtCurrentLoanAmount.getText()) == 0) 
        {
            JOptionPane.showMessageDialog(this, "Please provide a positive remaining balance of the current loan.",
           "Error", JOptionPane.ERROR_MESSAGE);
            txtCurrentLoanAmount.setText("");
            txtCurrentLoanAmount.requestFocusInWindow();
            return;
        } else {
            currentLoanAmount = Double.parseDouble(txtCurrentLoanAmount.getText());
        }   
        if (cboxOptions.getSelectedIndex() == 0)
        {              
            // current monthly payment
            if (txtCurrentMonthlyPayment.getText().equals("")) 
            {
                JOptionPane.showMessageDialog(this, "Please provide a positive monthly payment amount of the current loan..",
               "Error", JOptionPane.ERROR_MESSAGE);
                txtCurrentMonthlyPayment.setText("");
                txtCurrentMonthlyPayment.requestFocusInWindow();
                return;
            } else {
                currentMonthlyPayment = Double.parseDouble(txtCurrentMonthlyPayment.getText());
            } 
        } // end if 
        else
        {                  
            // original loan term - in months
            if (txtOriginalLoanTerm.getText().equals("") || Double.parseDouble(txtOriginalLoanTerm.getText()) > 51) 
            {
                JOptionPane.showMessageDialog(this, "Please provide a positive loan term that is 50 years or less.",
               "Error", JOptionPane.ERROR_MESSAGE);
                txtOriginalLoanTerm.setText("");
                txtOriginalLoanTerm.requestFocusInWindow();
                return;
            } else {
                originalLoanTerm = Math.floor(Double.parseDouble(txtOriginalLoanTerm.getText()) * 12) ;
            }                  
            // original loan remaining years - in months
            if (txtTimeRemainingYears.getText().equals("")) 
            {
                JOptionPane.showMessageDialog(this, "Please provide a positive remaining year and month value.",
               "Error", JOptionPane.ERROR_MESSAGE);
                txtTimeRemainingYears.setText("");
                txtTimeRemainingYears.requestFocusInWindow();
                return;
            } else {
                originalLoanRemainingYears = Math.floor(Double.parseDouble(txtTimeRemainingYears.getText()) * 12);
            }                       
            // original loan remaining months
            if (txtTimeRemainingMonths.getText().equals("")) 
            {
                JOptionPane.showMessageDialog(this, "Please provide a positive remaining year and month value.",
               "Error", JOptionPane.ERROR_MESSAGE);
                txtTimeRemainingMonths.setText("");
                txtTimeRemainingMonths.requestFocusInWindow();
                return;
            } else {
                originalLoanRemainingMonths = Math.floor(Double.parseDouble(txtTimeRemainingMonths.getText()));
            }
        } // end else
        
        if ((originalLoanRemainingYears + originalLoanRemainingMonths) > originalLoanTerm)
        {
            JOptionPane.showMessageDialog(this, "Please provide a positive remaining year and month value.",
               "Error", JOptionPane.ERROR_MESSAGE);
                txtTimeRemainingYears.setText("");
                txtTimeRemainingMonths.setText("");
                txtTimeRemainingYears.requestFocusInWindow();
                return;
        }
        
                  
        // current interest rate
        if (txtCurrentInterestRate.getText().equals("") || Double.parseDouble(txtCurrentInterestRate.getText()) > 200) 
        {
            JOptionPane.showMessageDialog(this, "Please provide a positive interest rate that is 200% or less.",
               "Error", JOptionPane.ERROR_MESSAGE);
                txtCurrentInterestRate.setText("");
                txtCurrentInterestRate.requestFocusInWindow();
                return;
        } else {
            currentInterestRate = Double.parseDouble(txtCurrentInterestRate.getText()) / 1200.0;
        }        
        // new loan term - in months
        if (txtNewLoanMonths.getText().equals("") || Double.parseDouble(txtNewLoanMonths.getText()) == 0 
                || Double.parseDouble(txtNewLoanMonths.getText()) > 400) 
        {
            JOptionPane.showMessageDialog(this, "Please provide a reasonable new loan term value.",
               "Error", JOptionPane.ERROR_MESSAGE);
            txtNewLoanMonths.setText("");
            txtNewLoanMonths.requestFocusInWindow();
            return;
        } else {
            newLoanMonths = Math.floor(Double.parseDouble(txtNewLoanMonths.getText()) * 12);
        }        
        // new loan interest rate
        if (txtNewInterestRate.getText().equals("") || Double.parseDouble(txtNewInterestRate.getText()) > 200) 
        {
            JOptionPane.showMessageDialog(this, "Please provide a positive interest rate that is 200% or less.",
               "Error", JOptionPane.ERROR_MESSAGE);
                txtNewInterestRate.setText("");
                txtNewInterestRate.requestFocusInWindow();
                return;
        } else {
            newInterestRate = Double.parseDouble(txtNewInterestRate.getText()) / 1200.0;
        }    
        // points
        if (txtPoints.getText().equals("") || Double.parseDouble(txtPoints.getText()) > 100) 
        {
            JOptionPane.showMessageDialog(this, "Please provide a point from 0 to 100.",
               "Error", JOptionPane.ERROR_MESSAGE);
                txtPoints.setText("");
                txtPoints.requestFocusInWindow();
                return;
        } else {
            points = Double.parseDouble(txtPoints.getText()) / 100.0;
        }
        // cost and fees
        if (txtCostFees.getText().equals("")) 
        {
            JOptionPane.showMessageDialog(this, "Please provide a positive cost value.",
               "Error", JOptionPane.ERROR_MESSAGE);
                txtCostFees.setText("");
                txtCostFees.requestFocusInWindow();
                return;
        } else {
            costFees = Double.parseDouble(txtCostFees.getText());
        }
        // cash out amount
        if (txtCashOutAmount.getText().equals("")) 
        {
            JOptionPane.showMessageDialog(this, "Please provide a numeric cash out amount.",
               "Error", JOptionPane.ERROR_MESSAGE);
                txtCashOutAmount.setText("");
                txtCashOutAmount.requestFocusInWindow();
                return;
        } 
        else if (Double.parseDouble(txtCashOutAmount.getText()) < 0 && Math.abs(Double.parseDouble(txtCashOutAmount.getText())) >= currentLoanAmount)
        {
            JOptionPane.showMessageDialog(this, "Cash out amount can not reduce balance amount to or below zero.",
               "Error", JOptionPane.ERROR_MESSAGE);
                txtCashOutAmount.setText("");
                txtCashOutAmount.requestFocusInWindow();
                return;
        }
        else
        {
            cashOutAmount = Double.parseDouble(txtCashOutAmount.getText());
        }
        
        
        //option specific operations
        if (cboxOptions.getSelectedIndex() == 0) // remaining balance option
        {
            
            if (currentMonthlyPayment <= currentLoanAmount * currentInterestRate) 
            {
                JOptionPane.showMessageDialog(this, "Monthly payment is too low to pay off the balance. Please enter a higher monthly payment",
               "Error", JOptionPane.ERROR_MESSAGE);
                txtCurrentMonthlyPayment.setText("");
                txtCurrentMonthlyPayment.requestFocusInWindow();
                return;
            }
       
            
            
            currentLoanMonths = Helper.months(currentLoanAmount, currentMonthlyPayment, currentInterestRate); //months
            totalCurrentMonthlyPayments = currentMonthlyPayment * currentLoanMonths; // total amount of payments made on current loan
            currentAccumulatedInterest = totalCurrentMonthlyPayments - currentLoanAmount; //accumulated interest for current loan
            newPrincipalFinal = currentLoanAmount + cashOutAmount; // updated remaining balance for new loan
            pointsCost = newPrincipalFinal * points; // cost of points on loan
            AprPrincipal = newPrincipalFinal - (pointsCost + costFees);
            
        }
        else // original amount option
        {
            
           // needed to find the remaining interest
            timeDifference = originalLoanTerm - (originalLoanRemainingYears + originalLoanRemainingMonths);
           //original loan monthly payment
            originalLoanMonthlyPayment = Helper.monthlyPayment(currentLoanAmount, originalLoanTerm, currentInterestRate);
           //interest for original loan option
            originalLoanInterest = Helper.originalAccumulatedInterest(currentLoanAmount, originalLoanMonthlyPayment, 
                currentInterestRate, timeDifference);
            //original loan principal updated
            newPrincipalOriginal = (originalLoanMonthlyPayment * (originalLoanRemainingYears + originalLoanRemainingMonths))
                   - originalLoanInterest;
            // total amount of payments made on current loan
            totalCurrentMonthlyPayments = newPrincipalOriginal + originalLoanInterest;
            newPrincipalFinal = newPrincipalOriginal + cashOutAmount;
            pointsCost = newPrincipalFinal * points; // cost of points on loan
            AprPrincipal = newPrincipalFinal - (pointsCost + costFees);
        }
        
        
        // new loan operations
        newMonthlyPayment = Helper.monthlyPayment(newPrincipalFinal, newLoanMonths, newInterestRate); //new loan monthly payment        
        //accumualted interest for new loan
        newAccumulatedInterest = Helper.remainingAccumulatedInterest(newPrincipalFinal, newMonthlyPayment, newInterestRate);
        totalNewMonthlyPayments = newPrincipalFinal + newAccumulatedInterest; // total amount of payments made on new loan
        // finding new apr
        double monthlyRate = Helper.calculateInterestRate(AprPrincipal, newMonthlyPayment, newLoanMonths, tolerance);
        double apr = monthlyRate * 12 * 100; // Convert monthly rate to annual percentage rate
        
        
        
        DefaultTableModel model = (DefaultTableModel) tblOutput.getModel();
        model.setRowCount(0);
        
        
        // option dependent output
        if (cboxOptions.getSelectedIndex() == 0) // table for remaining balance
        {
            model.addRow(new Object[]{"Principal/loan amount", "$" + Helper.formatDouble(currentLoanAmount), "$" + Helper.formatDouble(newPrincipalFinal), 
                "$" + Helper.formatDouble(newPrincipalFinal - currentLoanAmount)});
            model.addRow(new Object[]{"Monthly Payment", "$" + Helper.formatDouble(currentMonthlyPayment), "$" + Helper.formatDouble(newMonthlyPayment), 
                "$" + Helper.formatDouble(newMonthlyPayment - currentMonthlyPayment)});
            model.addRow(new Object[]{"Length (months)", currentLoanMonths, newLoanMonths, newLoanMonths - currentLoanMonths});
            model.addRow(new Object[]{"Interest Rate/APR", Helper.formatAPR(currentInterestRate * 1200.0) + "%", Helper.formatAPR(apr) + "%", 
                Helper.formatAPR(apr - (currentInterestRate * 1200)) + "%"});
            model.addRow(new Object[]{"Total Monthly Payment", "$" + Helper.formatDouble(totalCurrentMonthlyPayments), 
                "$" + Helper.formatDouble(totalNewMonthlyPayments), "$" + Helper.formatDouble(totalNewMonthlyPayments - totalCurrentMonthlyPayments)});
            model.addRow(new Object[]{"Total Interest", "$" + Helper.formatDouble(currentAccumulatedInterest),
                "$" + Helper.formatDouble(newAccumulatedInterest), "$" + Helper.formatDouble(newAccumulatedInterest - currentAccumulatedInterest)});
            model.addRow(new Object[]{"Cost + points (upfront)", "$" + 0, "$" + Helper.formatDouble(pointsCost + costFees)});
            model.addRow(new Object[]{"Cash out", "$" + 0, "$" + Helper.formatDouble(cashOutAmount)});
            if (cashOutAmount != 0)
            {
                model.addRow(new Object[]{"Take home amount after cost/point", "$" + 0, "$" 
                        + Helper.formatDouble(cashOutAmount - (pointsCost + costFees))});
            }
 }
        else
        {
            model.addRow(new Object[]{"Principal/loan amount", "$" + Helper.formatDouble(newPrincipalOriginal),
                "$" + Helper.formatDouble(newPrincipalFinal), "$" + Helper.formatDouble(newPrincipalFinal - newPrincipalOriginal)});
            model.addRow(new Object[]{"Monthly Payment", "$" + Helper.formatDouble(originalLoanMonthlyPayment), 
                "$" + Helper.formatDouble(newMonthlyPayment), "$" + Helper.formatDouble(newMonthlyPayment - originalLoanMonthlyPayment)});
            model.addRow(new Object[]{"Length (months)", originalLoanRemainingYears + originalLoanRemainingMonths, newLoanMonths, 
                newLoanMonths - (originalLoanRemainingYears + originalLoanRemainingMonths)});
            model.addRow(new Object[]{"Interest Rate/APR", Helper.formatAPR(currentInterestRate * 1200.0) + "%",
                Helper.formatAPR(apr) + "%", Helper.formatAPR(apr - (currentInterestRate * 1200)) + "%"});
            model.addRow(new Object[]{"Total Monthly Payment", "$" + Helper.formatDouble(totalCurrentMonthlyPayments), 
                "$" + Helper.formatDouble(totalNewMonthlyPayments), "$" + Helper.formatDouble(totalNewMonthlyPayments - totalCurrentMonthlyPayments)});
            model.addRow(new Object[]{"Total Interest", "$" +Helper.formatDouble(originalLoanInterest), 
                "$" + Helper.formatDouble(newAccumulatedInterest), "$" + Helper.formatDouble(newAccumulatedInterest - originalLoanInterest)});
            model.addRow(new Object[]{"Cost + points (upfront)", "$" + 0, "$" + Helper.formatDouble(pointsCost + costFees)});
            model.addRow(new Object[]{"Cash out", "$" + 0, "$" + Helper.formatDouble(cashOutAmount)});
            if (cashOutAmount != 0)
            {
                model.addRow(new Object[]{"Take home amount after cost/point", "$" + 0, "$" 
                        + Helper.formatDouble(cashOutAmount - (pointsCost + costFees))});
            }

        } //table for original loan
        
        if (cboxOptions.getSelectedIndex() == 0) //remaining balance
        {
            if ((newMonthlyPayment - currentMonthlyPayment) > 0)
            {
                lblResults.setText("<HTML>New monthly payment: $" + Helper.formatDouble(newMonthlyPayment) + 
                    "<br/>$" + Helper.formatDouble(newMonthlyPayment - currentMonthlyPayment) + "/month extra cost in monthly pay"
            + "<br/>$" + Helper.formatDouble(pointsCost + costFees + newAccumulatedInterest) + " total extra cost for the new loan"
            + "<br/>$" + Helper.formatDouble(pointsCost + costFees) + " upfront cost<HTML>");
            }
            else
            {
                lblResults.setText("<HTML>New monthly payment: $" + Helper.formatDouble(newMonthlyPayment) + 
                    "<br/>$" + Helper.formatDouble(Math.abs(newMonthlyPayment - currentMonthlyPayment)) + "/month savings in monthly pay"
            + "<br/>$" + Helper.formatDouble(pointsCost + costFees + newAccumulatedInterest) + " total extra cost for the new loan"
            + "<br/>$" + Helper.formatDouble(pointsCost + costFees) + " upfront cost<HTML>");
            }
        }
        else // original loan
        {
            
            if ((newMonthlyPayment - originalLoanMonthlyPayment) > 0) // pays extra
            {
                if (cashOutAmount <= 0)
                {
                    double totalExtra = Math.abs(cashOutAmount) + pointsCost + costFees + (totalNewMonthlyPayments - totalCurrentMonthlyPayments);
                    lblResults.setText("<HTML>New monthly payment: $" + Helper.formatDouble(newMonthlyPayment) + 
                    "<br/>$" + Helper.formatDouble(newMonthlyPayment - originalLoanMonthlyPayment) + "/month extra cost in monthly pay"
            + "<br/>$" + Helper.formatDouble(totalExtra) + 
                            " total extra cost for the new loan"
            + "<br/>$" + Helper.formatDouble(pointsCost + costFees) + " upfront cost<HTML>");
                }
                else
                {
                    double totalExtra = (totalNewMonthlyPayments - totalCurrentMonthlyPayments) - (cashOutAmount - (pointsCost + costFees));
                    lblResults.setText("<HTML>New monthly payment: $" + Helper.formatDouble(newMonthlyPayment) + 
                    "<br/>$" + Helper.formatDouble(newMonthlyPayment - originalLoanMonthlyPayment) + "/month extra cost in monthly pay"
            + "<br/>$" + Helper.formatDouble(totalExtra) + " total extra cost for the new loan"
            + "<br/>$" + Helper.formatDouble(pointsCost + costFees) + " upfront cost<HTML>");
            }
                }
                
            else // saves extra
            {
                if (cashOutAmount <= 0)
                {
                    double totalExtra = Math.abs(cashOutAmount) + pointsCost + costFees + (totalNewMonthlyPayments - totalCurrentMonthlyPayments);
                    lblResults.setText("<HTML>New monthly payment: $" + Helper.formatDouble(newMonthlyPayment) + 
                    "<br/>$" + Helper.formatDouble(Math.abs(newMonthlyPayment - originalLoanMonthlyPayment)) + "/month savings in monthly pay"
            + "<br/>$" + Helper.formatDouble(totalExtra) + " total extra cost for the new loan"
            + "<br/>$" + Helper.formatDouble(pointsCost + costFees) + " upfront cost<HTML>");
                } // end if
                else
                {
                    double totalExtra = (totalNewMonthlyPayments - totalCurrentMonthlyPayments) - (cashOutAmount - (pointsCost + costFees));
                    lblResults.setText("<HTML>New monthly payment: $" + Helper.formatDouble(newMonthlyPayment) + 
                    "<br/>$" + Helper.formatDouble(Math.abs(newMonthlyPayment - originalLoanMonthlyPayment)) + "/month savings in monthly pay"
            + "<br/>$" + Helper.formatDouble(totalExtra) + " total extra cost for the new loan"
            + "<br/>$" + Helper.formatDouble(pointsCost + costFees) + " upfront cost<HTML>");
                } // end else
                
            } // end else
        }// end else 
        
        
        
        if (apr - (currentInterestRate * 1200) > 0.00002)
        {
            lblAprOutput.setText("<HTML>The APR for the new loan is " + Helper.formatAPR(apr)+ "%,"
                + " which is " +  Helper.formatAPR(apr - (currentInterestRate * 1200)) + "% higher than the "
                + (currentInterestRate * 1200) + "% interest rate of the current loan. " 
                        + " Refinancing would be financially more expensive.<HTML>");
            
        }
        else if (apr - (currentInterestRate * 1200) < 0)
        {
            lblAprOutput.setText("<HTML>The APR for the new loan is " + Helper.formatAPR(apr)+ "%,"
                + "\n which is " +  Helper.formatAPR(Math.abs((apr - (currentInterestRate * 1200)))) + "% lower than the "
                + (currentInterestRate * 1200) + "% interest rate of the current loan. " 
                        + " Refinancing would be financially less expensive.<HTML>");
        }
        else
        {
            lblAprOutput.setText("<HTML>The APR for the new loan is " + Helper.formatAPR(apr)+ "%,"
                + " which is similar to the " + (currentInterestRate * 1200) + "% interest rate of the current loan." 
                        + " The financial cost of the new loan is comparable to that of the existing loan.<HTML>");
        }
        
        
        

    // end button
    }//GEN-LAST:event_btnCalculateMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        txtCurrentLoanAmount.setText("");
        txtCurrentMonthlyPayment.setText("");
        txtCurrentInterestRate.setText("");
        txtNewLoanMonths.setText("");
        txtNewInterestRate.setText("");
        txtPoints.setText("");
        txtCostFees.setText("");
        txtCashOutAmount.setText("");
        // original loan
        txtOriginalLoanTerm.setText("");
        txtTimeRemainingYears.setText("");
        txtTimeRemainingMonths.setText("");
        txtCurrentLoanAmount.requestFocusInWindow();
  
        lblAprOutput.setText("");
        lblResults.setText("");
        DefaultTableModel model = (DefaultTableModel) tblOutput.getModel();
        model.setRowCount(0);

        
        
    }//GEN-LAST:event_btnClearMouseClicked

    private void cboxOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxOptionsActionPerformed

        if (cboxOptions.getSelectedIndex() == 0)
        {
            txtCurrentMonthlyPayment.setVisible(true);
            lblCurrentLoanAmount.setText("Remaining balance");
            lblMonthlyPayment.setVisible(true);
            txtCurrentInterestRate.setText("");
            // original loan
            lblCurrentLoanTerm.setVisible(false);
            lblTimeRemaining.setVisible(false);
            txtOriginalLoanTerm.setVisible(false);
            txtTimeRemainingYears.setVisible(false);
            txtTimeRemainingMonths.setVisible(false);
            lblYears.setVisible(false);
            lblYears1.setVisible(false);
            lblMonths.setVisible(false);
            lblAprOutput.setText("");
            lblResults.setText("");


        }
        else
        {
            txtCurrentMonthlyPayment.setVisible(false);
            lblCurrentLoanAmount.setText("Original loan amount");
            lblMonthlyPayment.setVisible(false);
            txtCurrentInterestRate.setText("");
            // original loan
            lblCurrentLoanTerm.setVisible(true);
            lblTimeRemaining.setVisible(true);
            txtOriginalLoanTerm.setVisible(true);
            txtTimeRemainingYears.setVisible(true);
            txtTimeRemainingMonths.setVisible(true);
            lblYears.setVisible(true);
            lblYears1.setVisible(true);
            lblMonths.setVisible(true);
            lblAprOutput.setText("");
            lblResults.setText("");
        }
    }//GEN-LAST:event_cboxOptionsActionPerformed

    private void txtOriginalLoanTermKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOriginalLoanTermKeyTyped
        Helper.consumeNotNumbersAllowDecimal(txtOriginalLoanTerm, evt);
    }//GEN-LAST:event_txtOriginalLoanTermKeyTyped

    private void txtTimeRemainingYearsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimeRemainingYearsKeyTyped
        Helper.consumeNotNumbersAllowDecimal(txtTimeRemainingYears, evt);
    }//GEN-LAST:event_txtTimeRemainingYearsKeyTyped

    private void txtTimeRemainingMonthsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimeRemainingMonthsKeyTyped
        Helper.consumeNotNumbersAllowDecimal(txtTimeRemainingMonths, evt);
    }//GEN-LAST:event_txtTimeRemainingMonthsKeyTyped

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseClicked
        new calc6HelpFrame().setVisible(true);
    }//GEN-LAST:event_btnHelpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHelp;
    private javax.swing.JComboBox<String> cboxOptions;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAprOutput;
    private javax.swing.JLabel lblCashOut;
    private javax.swing.JLabel lblCostsFees;
    private javax.swing.JLabel lblCurrentInterestRate;
    private javax.swing.JLabel lblCurrentLoan;
    private javax.swing.JLabel lblCurrentLoanAmount;
    private javax.swing.JLabel lblCurrentLoanTerm;
    private javax.swing.JLabel lblMonthlyPayment;
    private javax.swing.JLabel lblMonths;
    private javax.swing.JLabel lblNewInterestRate;
    private javax.swing.JLabel lblNewLoan;
    private javax.swing.JLabel lblNewLoanTerm;
    private javax.swing.JLabel lblPercent1;
    private javax.swing.JLabel lblPercent2;
    private javax.swing.JLabel lblPoints;
    private javax.swing.JLabel lblResults;
    private javax.swing.JLabel lblTimeRemaining;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblYears;
    private javax.swing.JLabel lblYears1;
    private javax.swing.JTable tblOutput;
    private javax.swing.JTextField txtCashOutAmount;
    private javax.swing.JTextField txtCostFees;
    private javax.swing.JTextField txtCurrentInterestRate;
    private javax.swing.JTextField txtCurrentLoanAmount;
    private javax.swing.JTextField txtCurrentMonthlyPayment;
    private javax.swing.JTextField txtNewInterestRate;
    private javax.swing.JTextField txtNewLoanMonths;
    private javax.swing.JTextField txtOriginalLoanTerm;
    private javax.swing.JTextField txtPoints;
    private javax.swing.JTextField txtTimeRemainingMonths;
    private javax.swing.JTextField txtTimeRemainingYears;
    // End of variables declaration//GEN-END:variables
}
